name: Build Debug APK

on:
  pull_request:
    branches: [ master, develop]
    types: [ closed ]

jobs:
  build:
    name: Test and deploy debug APK

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Access SUB_API_KEY
      env:
        SUB_API_KEY: ${{ secrets.SUB_API_KEY }}
      run: echo SUB_API_KEY=\"$SUB_API_KEY\" > ./local.properties
    - name: Build with Gradle after putting API KEY
      run: ./gradlew build
    - name: Run Kotlin Linter
      run: ./gradlew ktlintCheck
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
    - name: Build with Gradle for debug APK
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Upload APK to workspace
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
    - name: Send debug APk to telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.BOT_TOKEN }}
        message: |
          Below is the apk for commit: ${{ github.event.head_commit.message }}
        document: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk`