# This is a basic workflow to help you get started with Actions

name: Issue Notifier

# Controls when the action will run. 
on:
  issues:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Send Issue event notification to telegram
        uses: appleboy/telegram-action@master
        with:
         to: ${{ secrets.CHAT_ID }}
         token: ${{ secrets.BOT_TOKEN }}
         message: |
          Issue event triggered! 
          Triggered by: ${{ github.actor }}
          Pay attention: ${{ secrets.MOEIN_ID }} & ${{ secrets.MAMAD_ID }}
