name: Testing latest push

on:
  push:

jobs:
  build:
    name: Test and build debug APK

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Access SUB_API_KEY
        env:
          SUB_API_KEY: ${{ secrets.SUB_API_KEY }}
        run: echo SUB_API_KEY=\"$SUB_API_KEY\" > ./local.properties
      - name: Build with Gradle after putting API KEY
        run: ./gradlew build
      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      - name: Build with Gradle for debug APK
        run: ./gradlew build
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Send PR confirmation to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            Testing latest push was succesfull
            latest commit description: ${{ github.event.head_commit.message }}
